services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER: ${USERNAME}
        JAVA_VERSION: ${JAVA_VERSION}
        NODE_VERSION: ${NODE_VERSION}

    restart: always
    volumes:
      - ./:/home/${USERNAME}/app
      - /home/${USERNAME}/.gitconfig:/home/${USERNAME}/.gitconfig
      - /home/${USERNAME}/.ssh:/home/${USERNAME}/.ssh

    tty: true
    network_mode: host

  postgres:
    image: postgres:${POSTGRES_VERSION}

    restart: always
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgres/data

    environment:
      POSTGRES_PASSWORD: dev
